# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    id: containerssh
    main: ./cmd/containerssh
    binary: containerssh
archives:
  - id: containerssh
    format: binary
    builds:
      - containerssh
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
dockers:
- image_templates:
  - "tensorchord/containerssh:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  ids:
  - containerssh
  build_flag_templates:
  - "--platform=linux/amd64"
docker_manifests:
- name_template: tensorchord/containerssh:{{ .Version }}
  image_templates:
  - tensorchord/containerssh:{{ .Version }}-amd64
